### ISSUE TITLE
I can' t find the definition of the function 'Reab3p16'

### ISSUE THREAD

**Issue by lvba** [zkcys001/distracting_feature#1]
Hello! I was about to run the code of your paper when I found that there is not any definition about the function 'Reab3p16' in the 96 row in the file 'trainer.py'.And I didn' t find any information about this problem in Readme file.So I wanna ask you about this. Thanks!

**Comment by zkcys001** [comment]
I am happy that you are interested in this code. I have already uploaded these missing files. If you have any questions, please feel free to contact me by email (zkcys001@mail.ustc.edu.cn).
